### PR TITLE
feat: embed dependencies

### PR DESCRIPTION
**Pull request by gyoshev**
Embeds the `bootstrap` and `kendo-theme-default` modules in the NPM package. Simplifies installs for customers as it allows use without installing dependencies.

part of telerik/kendo-theme-bootstrap#256

/cc @tsvetomir

### CODE REVIEW

**Comment by kibbled** [comment]
This feature also increases the risk of compatibility breakages with things like Bootstrap. See: https://github.com/telerik/kendo-theme-bootstrap/issues/341

**Comment by gyoshev** [comment]
Even if the embedded variables are removed, it does not get any less risky. It is normal to have breaking changes between betas, because this is how semantic versioning defines prereleases. Let's continue a more focused discussion in the opened issue.

**Comment by kibbled** [comment]
Yea it's entirely understandable. About once a month Bootstrap breaks our own styling themes so I can relate.

One thing I'm curious about is what the reason that the Kendo Bootstrap theme imports Bootstrap's _variables.scss. If someone decides to import the version of Bootstrap bundled with Kendo then they would get _variables.scss imported anyway.

**Comment by gyoshev** [comment]
I think that the theme imports the variables for two reasons:

1. Minor updates to the Bootstrap variables are automatically fetched through an `npm update`. This does not work that well during betas, but should improve once the variables are stable.
2. (and more important) The Bootstrap theme does not require the use of the Bootstrap framework on the page to function correctly. Similarly, the theme can be compiled without prior knowledge of the Bootstrap variables.

I hope this puts the decision in perspective. Suggestions for improvement are always welcome :)

**Comment by kibbled** [comment]
@gyoshev A user of the kendo-theme-bootstrap framework needs to import Bootstrap anyway, whether it's the Kendo bundled version or another version from NPM. When Bootstrap is imported the correct associated _variables.scss already will get imported. Unless I'm missing something, importing _variables.scss twice is not necessary/redundant. Since _variables is always imported by Kendo there's no way to unimport it.

**Comment by gyoshev** [comment]
> A user of the kendo-theme-bootstrap framework needs to import Bootstrap anyway

No, it is not required; the import of _variables.scss in the theme makes sure that the proper version of bootstrap is included, and users of the framework do not need to include bootstrap. To illustrate,

```scss
@import "~@progress/kendo-theme-bootstrap/scss/all";
```

... will work even if no version of bootstrap is included in the scss source. It will also work if the correct version of the bootstrap source is included, without issue.

The only compatibility issue that may arise is if a different version of bootstrap is used (e.g. beta2), which we do not support at the moment. If the variables continue to change after the final release of the Bootstrap framework and yield breaking changes, we can think of options to support this. Right now, use the first Bootstrap beta until #342 is merged.

**Pull request merged**
